cache: cargo
dist: trusty
language: rust
rust: stable
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=svd2rust
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  include:
    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-musl

install:
  # `std for cross-compilation
  - curl https://static.rust-lang.org/rustup.sh |
    sh -s -- --add-target=$TARGET --disable-sudo -y --prefix=`rustc --print sysroot`

script:
  - cargo generate-lockfile
  - if [[ $TRAVIS_OS_NAME = linux ]]; then
      sh ci/run-docker.sh $TARGET;
    else
      sh ci/run.sh;
    fi
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

before_deploy:
  - sh ci/package.sh $TARGET

deploy:
  provider: releases
  api_key:
    secure: VVKAMdGkhZE0xIvT4c8eHJzVxgaIwreehVQ9d/H8sPxPjw4o1H3eFShEVqF0ynADVhNEIa/+gX8Bh4XQJVmd83vdj++3LaZVgSEx4rmUvBxvp9VfyyXnLKnhBnXQ74C+WldBYpR9LUXYbp4Zluo92eabZKkEUYAA4a+6h+4+d8r3vVd2DlxvkXKIwxltPggeVVzo/YO2y4TZ8fYeglisNp8oPSqyOM2ckzzM5J5+h28PRL0U64/CIGa2kgEXVm2zOw3rMiN4/KjBg3IXN/Q2LyWEPp6ntVQnBanXd/pveKRD9I5g4fLlJjSKvApV9X0T1o/3jeBxevFcH8b6UBSfY4zUfEdgQ/mIeeKpc8QwtA65sepJRtRDTOG2AR5yDD3hA8DBkslQPEeJISlpK46fZq738GR+pOHDM6y6r6R7QpMtJ1sdKTr4P7CPWhpczL4Y19S7cZMe4iPXRUtQRfOPB6GR8UHXZlNhA4WsTSMuvrhVoFt/FsWhZKEhkq9mxsdz5uipvr2YhbHorRZWVLyS8+ElNyWUjRDTNXmJ6yh97xIiyT0fGOnIpldP4jPcf5aZgwDx+9sqGkSabJnH8Oxkg6n8byjRy0BizAnKBi/ZxTkbx8HxHIUrnCeb+Nh7325xRsNrV/zHTnmiSQhXCY83ME6PQbbZwde2fr0yAyVpMPc=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  # don't delete the target directory
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - auto
    - try

notifications:
  email:
    on_success: never
