environment:
  global:
    CRATE_NAME: svd2rust
    RUST_VERSION: nightly
  matrix:
    - TARGET: i686-pc-windows-gnu
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: ci\install.ps1

build: false

test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target %TARGET%
    ) else (
      cargo rustc --target %TARGET% --release --bin svd2rust -- -C lto
    )

before_deploy:
  - ps: ci\package.ps1

deploy:
  description: 'Windows release'
  artifact: /.*\.zip/
  auth_token:
    secure: 3hcvyH2P2zpMR2EzdPL/P/NdcaVs6VLKfUMLx6TiMnzEpr51StkuyDGzWq8CDSb0
  provider: GitHub
  on:
    RUST_VERSION: nightly
    appveyor_repo_tag: true

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - auto
    - try

notifications:
  - provider: Email
    on_build_success: false
